// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class AppConfig {
  final bool isBootstrapNode;
  final String relayAddress;
  final List<String> bootstrapNodes;
  final int listenPort;

  const AppConfig({
    required this.isBootstrapNode,
    required this.relayAddress,
    required this.bootstrapNodes,
    required this.listenPort,
  });

  @override
  int get hashCode =>
      isBootstrapNode.hashCode ^
      relayAddress.hashCode ^
      bootstrapNodes.hashCode ^
      listenPort.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AppConfig &&
          runtimeType == other.runtimeType &&
          isBootstrapNode == other.isBootstrapNode &&
          relayAddress == other.relayAddress &&
          bootstrapNodes == other.bootstrapNodes &&
          listenPort == other.listenPort;
}
