fn main() {
    // This tells the Rust compiler that 'frb_expand' is a valid configuration condition
    // and suppresses the warnings generated by flutter_rust_bridge macros.
    println!("cargo:rustc-check-cfg=cfg(frb_expand)");
}