// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `MyP2PBehaviourEvent`, `MyP2PBehaviour`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `fmt`, `handle_established_inbound_connection`, `handle_established_outbound_connection`, `handle_pending_inbound_connection`, `handle_pending_outbound_connection`, `on_connection_handler_event`, `on_swarm_event`, `poll`

String startP2PNode() => RustLib.instance.api.crateApiNodeStartP2PNode();
