// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../config.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

void sendMessage({required String recipient, required String msg}) => RustLib
    .instance
    .api
    .crateApiNodeSendMessage(recipient: recipient, msg: msg);

Stream<String> startP2PNode({
  required String storagePath,
  required String instanceName,
  required AppConfig config,
}) => RustLib.instance.api.crateApiNodeStartP2PNode(
  storagePath: storagePath,
  instanceName: instanceName,
  config: config,
);

void refreshNode() => RustLib.instance.api.crateApiNodeRefreshNode();
